//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confirmations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Confirmations()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Id { get; set; }
        public System.DateTimeOffset Date { get; set; }
        public decimal Signal { get; set; }
        public int CandleStickId { get; set; }
        public int SetupId { get; set; }
    
        public virtual CandleSticks CandleSticks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Setups Setups { get; set; }
    }
}
