//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeApp.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Setups()
        {
            this.Confirmations = new HashSet<Confirmations>();
        }
    
        public int Id { get; set; }
        public System.DateTimeOffset Date { get; set; }
        public int Type { get; set; }
        public decimal Target { get; set; }
        public int CandleStickId { get; set; }
    
        public virtual CandleSticks CandleSticks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Confirmations> Confirmations { get; set; }
    }
}
