//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeApp.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TradeAppDBEntities : DbContext
    {
        public TradeAppDBEntities()
            : base("name=TradingAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CandleSticks> CandleSticks { get; set; }
        public virtual DbSet<Confirmations> Confirmations { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Setups> Setups { get; set; }
    }
}
